name: PR
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *' # daily

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package.json') }} # or package-lock.json
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install -g aws-cdk
      - run: sudo apt-get install jq

      # "1004153 is a transitive dep of mapbox-gl, which would be a significant upgrade"
      - run: "npm audit --production --json | jq -c '.advisories | keys[] | select( . as $in | ['1004153'] | index($in) | not)' | grep '.\\+'; exit $(( $? != 1 ? $? : 0 ))"
      - run: npm run test
      # - run: npm run lint # too many problems!

      - run: yarn install && yarn build && cd cdk && yarn install && npm run build && cdk synth