name: PR
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *' # daily

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package.json') }} # or package-lock.json
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: run npm audit
        run: npm audit --production

      - name: Run tests # LOL, there are none
        run: npm run test

      # - name: Run CDK synth
        # run: cdk synth